<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-plus'></i>
                        <span>Thêm sản phẩm mới</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            
                            <li>                                
                                <button class="btn btn-primary" onclick="submitform();"><i class="icon-save"></i> Lưu</button>
                            </li> 
                            <li>                                
                                <button class="btn btn-primary" onclick="resetform();"><i class="icon-refresh"></i> Nhập lại</button>
                            </li>
                            <li>
                                <a href='<?php echo WEB_PATH.'/system/product'?>'>
                                    <button class="btn btn-primary"><i class="icon-arrow-left"></i> Quay lại</button>
                                    
                                </a>
                             </li> 

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box'>
                    <?php
                    if(isset($alert)){
                        echo $alert;
                    }
                    ?>
                    <div class='box-header'>
                        <!--<div class='title'>Add User</div>-->
                        <button rel=".tab-content1" class="btn background-new">Thông tin chung</button>
                        <button rel=".tab-content2" class="btn"> Mô tả sản phẩm</button>
                        <button rel=".tab-content3" class="btn"> Hình ảnh</button>
                        <!--<button rel=".tab-content3" class="btn"> Video</button>-->
                        <button rel=".tab-content4" class="btn">Cấu hình SEO</button>
                        <!--<div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>-->
                    </div>
                    <div class='box-content'>
                        <form method="post" id="form-admin" class='form form-horizontal validate-form' style='margin-bottom: 0;'  enctype="multipart/form-data">
                            <div class="content-tab tab-content1">
                                <div class="row">   
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_name'>Tên sản phẩm</label>
                                        <div class='col-sm-9 controls'>
                                            <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_name' name="name"  placeholder='Tên sản phẩm' type='text' >
                                        </div>
                                    </div>
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_name'>Mã sản phẩm</label>
                                        <div class='col-sm-9 controls code_pro'>
                                            <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='code-product' name="code_id"  placeholder='Mã sản phẩm' type='text' >
                                            <i class="icon-refresh" onclick="get_codeproduct();"></i>
                                        </div>
                                       
                                    </div>
                                </div>
                                  <div class="row"> 
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_select'>Danh mục</label>
                                        <div class='col-sm-9 controls'>
                                            <select class='form-control' data-rule-required="true" id="validation_select2" name='cat_id'>
                                                <option value=""> Chọn danh mục</option>
                                                <?php foreach ($data_cat as $key=>$value){
                                                    if($value['parent']=='0'){
                                                        $PARENT_2 =$data_parent[$value['id']];                                                        
                                                    ?>
                                                <option value="<?php echo $value['id']?>"><?php echo $value['name']?></option>
                                                <?php
                                                //cấp 2
                                                if(count($PARENT_2)>0){
                                                    foreach ($PARENT_2 as $k2=>$vl2){
                                                        echo '<option value="'.$vl2['id'].'">- - '.$vl2['name'].'</option>';
                                                    //cấp 3
                                                        $PARENT_3=$data_parent[$vl2['id']];
                                                        if(count($PARENT_3)>0){
                                                            foreach ($PARENT_3 as $k3=>$vl3){
                                                                 echo '<option value="'.$vl3['id'].'">- - - -'.$vl3['name'].'</option>';
                                                            }
                                                        }//End cấp 3
                                                    }
                                                    
                                                }//End cấp 2
                                                ?>
                                              
                                                <?php                                                 
                                                    }
                                                }//End cấp 1
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_select'>Hãng sản xuất</label>
                                        <div class='col-sm-9 controls'>
                                            <select class='form-control'  id="validation_select1" name='manufa_id'>
                                                <option value=""> Chọn hãng sản xuất</option>
                                               <?php foreach ($data_manu as $key1=>$value1){?>
                                                <option value="<?php echo $value1['id']?>"><?php echo $value1['manu_name']?></option>
                                                <?php }?>
                                            </select>
                                        </div>
                                    </div>
                                  </div>
                                  <div class="row"> 
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_name'>Số lượng</label>
                                        <div class='col-sm-9 controls'>
                                            <input class='form-control'  id='validation_name2' name="quantity"  placeholder='Số lượng' type='number' >
                                        </div>
                                    </div> 
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_select'>Trạng thái</label>
                                        <div class='col-sm-9 controls'>
                                            <select class='form-control' data-rule-required="true" id="validation_select"  name='status_pro'>
                                                 <option value="Đang bán">Đang bán</option>
                                                <option value="Tạm hết hàng"> Tạm hết hàng</option>
                                                <option value="Ngừng kinh doanh"> Ngừng kinh doanh</option>
                                            </select>
                                        </div>
                                    </div>
                                  </div>
                                  <div class="row"> 
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_name'>Giá sản phẩm</label>
                                        <div class='col-sm-9 controls'>
                                            <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_name3' name="price"  placeholder='Giá sản phẩm' type='text' >
                                        </div>
                                    </div>
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_name'>Đơn vị tính</label>
                                        <div class='col-sm-9 controls'>
                                            <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_name4' name="product_dv"  placeholder='Đơn vị tính' type='text' >
                                        </div>
                                    </div>
                                  </div>
                                  <div class="row"> 
                                    <div class="form-group col-sm-6">
                                        <label class="col-md-3 control-label">Khuyến mại</label>
                                        <div class="col-sm-9">
                                            <label class="radio radio-inline">
                                                <input type="radio" onclick="getsales();" value="1" name="sales" >
                                                Có
                                            </label>
                                            <label class="radio radio-inline">
                                                <input type="radio" onclick="getsales();" value="0" name="sales">
                                                Không 
                                            </label>

                                        </div>
                                    </div>
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_sales'>Giá khuyến mại</label>
                                        <div class='col-sm-9 controls'>
                                            <input class='form-control' disabled="" data-rule-required='true' data-rule-minlength='1'  id='validation_sales' name="price_sales"  placeholder='Nhập phần trăm khuyến mại' type='text' >
                                        </div>
                                    </div>
                                  </div>
                                  <div class="row"> 
                                    <div class="form-group col-sm-6">
                                        <label class="col-md-3 control-label">Hiển thị</label>
                                        <div class="col-sm-9">
                                            <label class="radio radio-inline">
                                                <input type="radio" value="1" name="status" checked>
                                                Có hiển thị
                                            </label>
                                            <label class="radio radio-inline">
                                                <input type="radio" value="0" name="status">
                                                Không  hiển thị
                                            </label>

                                        </div>
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <label class="col-md-3 control-label">Sản phẩm nổi bật</label>
                                        <div class="col-sm-9">
                                            <label class="radio radio-inline">
                                                <input type="radio" value="1" name="pro_featured" >
                                                Có
                                            </label>
                                            <label class="radio radio-inline">
                                                <input type="radio" value="0" name="pro_featured">
                                                Không 
                                            </label>

                                        </div>
                                    </div>
                                  </div>
                                <div class="row">   
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_select'> Xuất xứ</label>
                                        <div class='col-sm-9 controls'>
                                            <select class='form-control'  id="validation_selectx" name='xuatxu'>
                                                <option value=""> Chọn xuất xứ</option>
                                               <?php foreach ($data_xuatxu as $keyx=>$valuex){?>
                                                <option value="<?php echo $valuex['id']?>"><?php echo $valuex['name']?></option>
                                                <?php }?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_select'> Chất liệu</label>
                                        <div class='col-sm-9 controls'>
                                            <select class='form-control'  id="validation_selectc" name='chatlieu'>
                                                <option value=""> Chọn chất liệu</option>
                                               <?php foreach ($data_chatlieu as $keyc=>$valuec){?>
                                                <option value="<?php echo $valuec['id']?>"><?php echo $valuec['name']?></option>
                                                <?php }?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                 <!--<div class="row"> 
                                      <div class='form-group col-sm-6'>
                                        <label class='control-label col-sm-3' for='validation_name'> Khoảng Giá</label>
                                        <div class='col-sm-9 controls code_pro'>
                                            <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='code-product1' name="khoanggia"  placeholder=' Khoảng giá' type='text' >
                                          
                                        </div>
                                       
                                    </div>
                                    <div class="form-group col-sm-6">
                                        <label class="col-md-3 control-label">Sản phẩm mới</label>
                                        <div class="col-sm-9">
                                            <label class="radio radio-inline">
                                                <input type="radio" value="1" name="pro_new" checked>
                                                Có
                                            </label>
                                            <label class="radio radio-inline">
                                                <input type="radio" value="0" name="pro_new">
                                                Không 
                                            </label>

                                        </div>
                                    </div>
                                  </div>-->
                                 <div class="row">
                                   <div class="form-group col-sm-6">
                                        <label class="col-md-3 control-label">Hiển thị trang chủ</label>
                                        <div class="col-sm-9">
                                            <label class="radio radio-inline">
                                                <input type="radio" value="1" name="show_index" >
                                                Có
                                            </label>
                                            <label class="radio radio-inline">
                                                <input type="radio" value="0" name="show_index">
                                                Không 
                                            </label>

                                        </div>
                                    </div>      
                                                         
                                 </div>
                                
                            </div>
                            <div class="content-tab tab-content2">
                                <div class="row">
                                    <div class='form-group col-sm-12'>
                                        <label class="col-sm-2 control-label">Mô tả tóm tắt</label>
                                        <div class="box-content col-sm-10">
                                            <textarea class="form-control ckeditor" data-rule-required="true" id="validation_name7" placeholder="Mô tả tóm tắt" name="description" rows="5"></textarea>
                                        </div>
                                    </div>


                                    <div class='form-group col-sm-12'>
                                        <label class="col-md-2 control-label">Mô tả chi tiết</label>
                                        <div class="box-content col-sm-10">
                                            <textarea name="content" class="form-control ckeditor" id="wysiwyg1" rows="10" >
                                            </textarea>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="content-tab tab-content3">
                                <div class="row">
                                    <div class='form-group col-sm-12'>
                                        <div class="col-sm-12">
                                        <p class="bg-warning controls">Cảnh Báo - Không được chọn hinh ảnh có nền trong suốt để tải lên và chỉ được chọn tối đa 5 ảnh 1 lân</p>
                                        </div>
                                        <div class='col-sm-8 controls'>                                                                                                 
                                           
                                             <input name="image[]" class="multi"   accept="jpeg|jpg|png" id="file" type='file'>
                                        </div>
                                        <div class="col-sm-4"><img style="width:100%"id="img" src="" /></div>

                                    </div>
                                    
                                </div>
                            </div>
                            <div class="content-tab tab-content4">
                                <div class="row">
                                    <div class='form-group col-sm-12'>
                                        <label class="col-sm-2 control-label">Tiêu đê</label>
                                        <div class="box-content col-sm-10">
                                            <textarea class="form-control" data-rule-required="true" id="validation_name7" placeholder="" name="seo_title" rows="5"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class='form-group col-sm-12'>
                                        <label class="col-sm-2 control-label">Meta Keyword</label>
                                        <div class="box-content col-sm-10">
                                            <textarea class="form-control" data-rule-required="true" id="validation_name7" placeholder="" name="seo_keyword" rows="5"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class='form-group col-sm-12'>
                                        <label class="col-sm-2 control-label">Meta Description</label>
                                        <div class="box-content col-sm-10">
                                            <textarea class="form-control" data-rule-required="true" id="validation_name7" placeholder="" name="seo_description" rows="5"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>              
    </div>
</div>
<style>
    .code_pro{
        position: relative;
    }
    .code_pro i{
        position: absolute;
        color: #c2100c;
        right: -15px;
        top:7px;
        cursor: pointer;
        font-size: 20px;
    }
    
</style>