<div class="box-slider-left">
    <div class="box-product">
        <h2 class="page-heading">
            <span>Khôi phục mật khẩu</span>
        </h2>

        <div class="box-contact">
            <div class="title-info top-20">
                Điền vào email của bạn để yêu cầu một mật khẩu mới. Một Email sẽ được gửi đến địa chỉ này để xác minh địa chỉ Email của bạn.
            </div>
            <br/>
            <?php
            if (isset($error)) {
                echo '<div class="alert alert-danger" role="alert">' . $error . '</div>';
            }
            if (isset($error1)) {
                echo '<div class="alert alert-success" role="alert">' . $error1 . '</div>';
            }
            ?> 


            <form class="form-horizontal" role="form" method="post" id="register-form">
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">
                        Email
                    </label>
                    <div class="col-sm-6">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Email">
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-6">
                        <button type="submit" class="button btn-send">Gửi thông tin
                        </button>

                    </div>
                </div>
            </form>
        </div>
        <div class="clear"></div>
    </div>

</div>