<form action="" id="logForm" method="post" class="form-horizontal">
				<input type="hidden" name="action" value="login"/>
					<div class="form-group">
						<div class="col-xs-12">
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
								<input type="text" name="username" class="form-control input-lg" placeholder="User" autocomplete="off">
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="col-xs-12">
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
								<input type="password" name="password" class="form-control input-lg" placeholder="Password" autocomplete="off">
							</div>
						</div>
					</div>
					<div class="form-group formSubmit">
						<div class="col-sm-7">
							<div class="checkbox">
								<label>
									<input type="checkbox" checked autocomplete="off"> Keep me logged in
								</label>
							</div>
						</div>
						<div class="col-sm-5 submitWrap">
							<button type="submit" name="login" class="btn btn-primary btn-lg">Log In</button>
						</div>
					</div>
					<div class="form-group formNotice">
						<div class="col-xs-12">
							<p class="text-center"><?php if(isset($thongbao)){ echo $thongbao;}?> </p>
						</div>
					</div>
				</form>