<?php
use Zend\Session\Container;
  $session_url_manu = new Container('urlmanu');     
  $alias= $session_url_manu->aliasmanu;
?>
<?php if ($this->pageCount): ?>
<div class="clear"></div>
    <div class="pagination pagination-centered">
        <ul>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('Hangsanxuat', array('alias'=>$alias,'page' => $this->first)); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('Hangsanxuat', array('alias'=>$alias, 'page' => $this->previous)); ?>">&lsaquo;</a></li>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('Hangsanxuat', array('alias'=>$alias,'page' => $page)); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('Hangsanxuat', array('alias'=>$alias, 'page' => $this->next)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('Hangsanxuat', array('alias'=>$alias, 'page' => $this->last)); ?>">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>