<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-th'></i>
                        <span>Thùng rác</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                           
                           
                            <li>
                                <a href='<?php echo WEB_PATH.'/system/product'?>'>
                                    <button class="btn btn-primary"><i class="icon-arrow-left"></i> Quay lại</button>
                                    
                                </a>
                             </li> 
                             <li>
                                <a href='<?php echo WEB_PATH.'/system/product/deleteall'?>'>
                                    <button class="btn btn-primary"><i class="icon-trash"></i> Xóa toàn bộ thùng rác</button>
                                    
                                </a>
                             </li> 
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box bordered-box orange-border' style='margin-bottom:0;'>
                   <!-- <div class='box-header blue-background'>
                        <div class='title'>List User</div>
                        <div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>
                    </div>-->
                    <div class='box-content box-no-padding'>
                        <div class='responsive-table'>
                            <div class='scrollable-area'>
                                <table class='data-table-column-filter table table-bordered table-striped' style='margin-bottom:0;'>
                                    <thead>
                                        <tr>
                                            <th>
                                               STT
                                            </th>
                                            <th>
                                                Hình ảnh
                                            </th>
                                            <th>
                                               Mã sản phẩm
                                            </th>
                                            <th>
                                             Tên sản phẩm
                                            </th>
                                            <th>
                                              Danh mục
                                            </th>                                            
                                             <th>
                                                 Ngày đăng
                                            </th>
                                             <th>
                                                 Ngày sửa
                                            </th>
                                             <th>
                                                 Action
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                                                               
                                        <?php 
                                        $stt='';
                                        foreach ($data as $key => $value) {
                                            $stt++;
                                            $id_product=$value['id'];
                                            ?>

                                            <tr>
                                                <td><?php echo $stt; ?></td>
                                                
                                                <td>
                                                    <?php if($id_product !=null){?>
                                                    <img src="<?php echo WEB_IMG.$data_img[$id_product]['thumbnail']?>" width="40" onerror=this.src="<?php echo WEB_IMG ?>/images/imgdefault.jpg" />
                                                    <?php } ?>
                                                </td>
                                                <td><?php echo $value['code_id']; ?></td>
                                                <td><?php echo $value['product_name']; ?></td>
                                                 <td><?php echo $value['name']; ?></td>
                                              
                                                
                                                <td><?php echo date('d-m-Y', strtotime($value['date'])); ?></td>
                                                <td><?php echo date('d-m-Y', strtotime($value['date_mod'])); ?></td>
                                                
                                                <td>
                                                    <div class='text-right'>
                                                        <a class='btn btn-info btn-xs' href='<?php echo WEB_PATH; ?>/system/product/trash/<?php echo $value['id'].'/trash-'.$value['delete_pro']; ?>'>
                                                            <i class='icon-retweet'></i>
                                                        </a>
                                                          <a onclick="deleteaction(<?php echo $value['id']?>)"class='btn btn-danger btn-xs'>
                                                            <i class='icon-trash'></i>
                                                        </a>
                                                    </div>
                                                    <input type="hidden" id="url" value="deleteproduct/" />
                                                </td>
                                            </tr>
                                        <?php } ?>
                                       
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th></th>
                                            <th></th>
                                            <th>Mã sản phẩm</th>
                                            <th>Tên sản phẩm</th>
                                            <th> Danh mục</th>
                                            <th>Ngày đăng</th>
                                            <th>Ngày sửa</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- //////////////////DELETE///////////////////--> 
<div class="modal fade" id="del" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header  blue-background">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                <h4 class="modal-title custom_align" id="Heading">XÓA SẢN PHẨM</h4>
            </div>
            <div class="modal-body">
                <p>Bạn có chắc chắn muốn xóa sản phẩm này. Mọi thông tin về sản phẩm sẽ bị xóa vĩnh viễn</p>

            </div>
            <div class="modal-footer ">
                <span id="btn-del"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
            </div>
        </div>
        <!-- /.modal-content --> 
    </div>
    <!-- /.modal-dialog --> 
</div>


<style>
    .select-pro select{
        font-size: 12px;
        height: 30px;
    }
</style>