
<!DOCTYPE html>
	<html lang="en">
		<head>
			<meta charset="utf-8">
			<meta http-equiv="X-UA-Compatible" content="IE=edge">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
			<meta name="description" content="A clean login and registration template based on Bootstrap framework">
			<meta name="author" content="">
			<link rel="shortcut icon" href="assets/ico/favicon.ico">

			<title>ADMIN - SYSTEM</title>

			<!-- Bootstrap core CSS -->
			<link href="<?php echo WEB_PUBLIC; ?>/login/css/bootstrap.min.css" rel="stylesheet">

			<!-- Custom styles for this template -->
			<link href="<?php echo WEB_PUBLIC; ?>/login/css/custom.css" rel="stylesheet">
			
			<link href="<?php echo WEB_PUBLIC; ?>/login/css/font-awesome.min.css" rel="stylesheet">
			<link media="screen" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,300italic">

			<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
			<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
			<![endif]-->
		</head>

		<body>
			<div id="mainWrap">
			<div id="loggit">
                            <!--<img src="<?php echo WEB_PUBLIC; ?>/login/img/logo.png"/>-->
				<?php echo $this->content;?>
				
			</div>

			</div>
			<footer class="clearfix">
				<p>Copyright &copy; 2015. All Rights Reserved</p>
			</footer>


			<!-- Bootstrap core JavaScript
			================================================== -->
			<!-- Placed at the end of the document so the pages load faster -->
			<script src="<?php echo WEB_PUBLIC; ?>/login/js/jquery.min.js"></script>
			<script src="<?php echo WEB_PUBLIC; ?>/login/js/bootstrap.min.js"></script>	
		</body>
</html>