<?php

use Zend\Session\Container;

$container = new Container('shopcart');
$arraycart = $container->cart;
?>

<!-- page heading-->
<h2 class="page-heading">
    <span class="page-heading-title2">Giỏ hàng</span>
</h2>
<?php
if ($arraycart == null) {
    echo '<div class="heading-counter warning">
    Giỏ hàng của bạn hiện tại không có sản phẩm nào.
    <a href="' . WEB_PATH . '">
     <button class="button">Tiếp Tục Mua Hàng</button>
     </a>
    </div>';
} else {
    ?>
    <div class="heading-counter warning">Giỏ hàng của bạn hiện có :
        <span><?php echo count($arraycart); ?> sản phẩm</span>
    </div>
    <!-- ../page heading-->
    <div class="page-content checkout-page">



        <div class="box-border">
            <table class="table table-bordered table-responsive cart_summary">
                <thead>
                    <tr>
                        <th class="cart_product">Hình ảnh</th>
                        <th> Tên sản phẩm</th>									
                        <th> Giá sản phẩm</th>
                        <th>Số lượng</th>
                        <th> Thành tiền</th>
                        <th  class="action"><i class="fa fa-trash-o"></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $total_money='';
                    foreach ($listproduct as $key => $value) { 
                         $qty = $arraycart[$value['id']];   
                        ?>
                        <tr>
                            <td class="cart_product">
                                <a href="<?php echo WEB_PATH . '/san-pham/' . $value['alias'] . '.html' ?>"><img src="<?php echo WEB_IMG .'images/'. $value['thumbnail'] ?>" alt="<?php echo $value['product_name'] ?>" width="100"></a>
                            </td>
                            <td class="cart_description">
                                <p class="product-name"><a href="<?php echo WEB_PATH . '/san-pham/' . $value['alias'] . '.html' ?>"><?php echo $value['product_name'] ?> </a></p>

                            </td>
                            <td class="price">
                                <?php
                                if ($value['sales'] == 1) {
                                    $price_sales = $value['price'] - ($value['price'] * $value['price_sales'] / 100);
                                    echo '<span class="price product-price">' . number_format($price_sales, 0, ',', '.') . 'đ / ' . $value['product_dv'] . '</span><br/>';
                                    echo '<span class="price old-price">' . number_format($value['price'], 0, ',', '.') . 'đ / ' . $value['product_dv'] . '</span>';
                                } else {
                                    $price_sales = $value['price'];
                                    echo '<span class="price product-price">' . number_format($value['price'], 0, ',', '.') . 'đ / ' . $value['product_dv'] . '</span>';
                                }
                                ?>    
                            </td>
                            <td class="qty">                               
                                <input type="hidden" id="qty_old" value="<?php echo $qty; ?>" />
                                <select onchange="updatecart(<?php echo $value['id']?>);" id="number-update" class="form-control input-sm">
                                <?php                                                   
                                for($i=0;$i<=$value['quantity'];$i++){
                                    if($i == $qty){
                                        $selected ='selected';
                                    }else{
                                         $selected ='';
                                    }
                                    if($i !=0){
                                    echo '<option value="'.$i.'" '.$selected.'>'.$i.'</option>';
                                    }
                                }
                                ?>
                                </select>
                                
                            </td>
                            <td class="price">
                                <?php                                
                                echo '<span class="price product-price">' . number_format($qty * $price_sales, 0, ',', '.') . 'đ</span><br/>';
                                ?>

                            </td>
                            <td class="action">
                                <a href="<?php echo WEB_PATH . '/shoppingcart/delete-items-cart/' . $value['id'] ?>">Delete item</a>
                            </td>
                        </tr>
                    <?php 
                    $total_money +=$qty * $price_sales;
                                } ?>
                </tbody>
                <tfoot>

                    <tr>
                        <td colspan="4"><strong>Tổng tiền</strong></td>
                        <td colspan="2"><strong><?php echo number_format($total_money, 0, ',', '.') . 'đ' ?></strong></td>
                    </tr>
                </tfoot>    
            </table>
            <a href="<?php echo WEB_PATH ?>">
            <button class="button pull-right">Tiếp Tục Mua Hàng</button>
            </a>
            <a href="<?php echo WEB_PATH . '/shoppingcart/clear-all-cart' ?>">
            <button class="button pull-right">Xóa Giỏ Hàng</button>
            </a>
            <a href="<?php echo WEB_PATH . '/shoppingcart/checkout.html' ?>">
            <button class="button pull-right">Thanh Toán</button>
            </a>
        </div>
    </div>
<?php } ?>