<?php
use Zend\Session\Container;
$session_key = new Container('urlsearch');
 $key=$session_key->key;;
?>
<?php if ($this->pageCount): ?>
<nav>
        <ul class="pagination">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('Search', array('page' => $this->first)).$key; ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('Search', array('page' => $this->previous)).$key; ?>">&lsaquo;</a></li>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('Search', array('page' => $page)).$key; ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('Search', array('page' => $this->next)).$key; ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('Search', array( 'page' => $this->last)).$key; ?>">&raquo;</a></li>
        </ul>
</nav>
<?php endif; ?>