<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-th'></i>
                        <span>Quản lí tài khoản</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            <li>
                                <a href='<?php echo WEB_PATH.'/system/add-user.html'?>'>
                                    <button class="btn btn-primary"><i class="icon-plus"></i> Thêm mới</button>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box bordered-box orange-border' style='margin-bottom:0;'>
                   <!-- <div class='box-header blue-background'>
                        <div class='title'>List User</div>
                        <div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>
                    </div>-->
                    <div class='box-content box-no-padding'>
                        <div class='responsive-table'>
                            <div class='scrollable-area'>
                                <table class='data-table-column-filter table table-bordered table-striped' style='margin-bottom:0;'>
                                    <thead>
                                        <tr>
                                            <th>
                                                Tài khoản
                                            </th>
                                            <th>
                                                Họ tên
                                            </th>
                                            <th>
                                                Nhóm quyền
                                            </th>
                                            <th>
                                                Ngày tạo
                                            </th>
                                            <th>
                                                Reset Password
                                            </th>																
                                            <th>
                                                Action
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>


                                        <?php foreach ($data as $key => $value) { ?>

                                            <tr>
                                                <td><?php echo $value['username']; ?></?php?></td>
                                                <td><?php echo $value['fullname']; ?></td>

                                                <td><?php
                                                    if ($value['permission'] == 1) {
                                                        echo 'Quản trị hệ thống';
                                                    } elseif($value['permission'] == 2 ) {
                                                        echo 'Cấu hình và quản lí nội dung website';
                                                    }elseif($value['permission'] == 3 ) {
                                                        echo 'Quản lí đơn hàng và sản phẩm';
                                                    }elseif($value['permission'] == 4 ) {
                                                        echo 'Quản lí  sản phẩm';
                                                    }
                                                    ;
                                                    ?>
                                                </td>
                                                <td><?php echo date('d-m-Y', strtotime($value['date'])); ?></td>
                                                <td>
                                                    <a onclick="ressetpass(<?php echo $value['id']; ?>)">
                                                        <span  class='label label-success'>Reset Password</span>
                                                    </a>
                                                </td>
                                                <td>
                                                    <div class='text-right'>
                                                        <a class='btn btn-primary btn-xs' href='<?php echo WEB_PATH; ?>/system/update-user-<?php echo $value['id']; ?>.html'>
                                                            <i class='icon-edit'></i>
                                                        </a>
                                                        <a onclick="delUser(<?php echo $value['id']; ?>)"class='btn btn-danger btn-xs'>
                                                            <i class='icon-remove'></i>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Username</th>
                                            <th> Fullname</th>
                                            <th colspan='2'> </th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- //////////////////DELETE///////////////////--> 
<div class="modal fade" id="del" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header  blue-background">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                <h4 class="modal-title custom_align" id="Heading">XÓA TÀI KHOẢN</h4>
            </div>
            <div class="modal-body">
                <p>Bạn có chắc chắn muốn xóa tài khoản này</p>

            </div>
            <div class="modal-footer ">
                <span id="btn-del"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
            </div>
        </div>
        <!-- /.modal-content --> 
    </div>
    <!-- /.modal-dialog --> 
</div>

<div class="modal fade" id="repass" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header  blue-background">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                <h4 class="modal-title custom_align" id="Heading"> Khôi phục mật khẩu</h4>
            </div>
            <div class="modal-body">
                <p> Khôi phục mật khẩu thành công</p>
                <p> Mật khẩu được khôi phục về mặc định là: 123456</p>

            </div>
            <div class="modal-footer ">
                <span id="btn-del"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
            </div>
        </div>
        <!-- /.modal-content --> 
    </div>
    <!-- /.modal-dialog --> 
</div>