<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-th'></i>
                        <span>Đơn hàng khách hàng <span style="color: red"><?php echo $data_customer['fullname']?></span></span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box bordered-box orange-border' style='margin-bottom:0;'>
                    <!-- <div class='box-header blue-background'>
                         <div class='title'>List User</div>
                         <div class='actions'>
                             <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                             </a>
 
                             <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                             </a>
                         </div>
                     </div>-->
                    <div class='box-content box-no-padding'>
                        <div class='responsive-table'>
                            <div class='scrollable-area'>
                                <table class='data-table-column-filter table table-bordered table-striped' style='margin-bottom:0;'>
                                    <thead>
                                        <tr>
                                            <th>
                                                Mã hóa đơn
                                            </th>
                                            <th>
                                               Tên khách hàng
                                            </th>
                                            <th>
                                              Tình trạng
                                            </th>
                                            <th>
                                                 Hình thức thanh toán
                                            </th>
                                            <th>
                                                Ngày đặt
                                            </th>
                                            <th>
                                                 Tổng tiền
                                            </th>																
                                            <th>
                                                Action
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>


                                        <?php
                                       
                                        foreach ($data as $key => $value) {
                                            
                                            ?>

                                            <tr>
                                                <td><?php echo $value->code_oder; ?></td>
                                                <td><?php echo $value->name; ?></td>
                                                <td>
                                                  <div class='col-sm-11 controls select-pro'>
                                             <select class='form-control' data-rule-required="true" id="status-oder" onchange="changestatus_oder(<?php echo $value['id']?>)" name='manufa_id'>
                                                <option <?php if($value['status_order']=='0'){ echo 'selected' ;}?> value="0">Đang chờ xử lý</option>
                                                <option <?php if($value['status_order']=='1'){ echo 'selected' ;}?> value="1"> Đang sử lý</option>
                                                <option <?php if($value['status_order']=='2'){ echo 'selected' ;}?> value="2">  Đã hoàn thành</option>
                                                 <option <?php if($value['status_order']=='3'){ echo 'selected' ;}?> value="3">  Hủy đơn hàng</option>
                                            </select>
                                        </div>
                                                </td>
                                                <td>
                                                    <?php 
                                                     if ($value->type == 1) {
                                                    echo 'Thanh toán tại cửa hàng';
                    }                                   else {
                                                     echo 'Thanh toán khi nhận được hàng';
                    }
                                                    ?>
                                                </td>
                                                <td><?php echo date('d-m-Y', strtotime($value->date)); ?></td>
                                                <td>
                                                    <?php echo number_format($value->total_money,0)?> VNĐ
                                                </td>


                                                <td>
                                                    <div class='text-right'>
                                                        <a class='btn btn-primary btn-xs' href='<?php echo WEB_PATH; ?>/system/order/view/<?php echo $value->id; ?>.html'>
                                                            <i class='icon-eye-open'></i>
                                                        </a>
                                                        <a onclick="deleteaction(<?php echo $value->id; ?>)"class='btn btn-danger btn-xs'>
                                                            <i class='icon-trash'></i>
                                                        </a>
                                                    </div>
                                                    <input type="hidden" id="url" value="order/delete/" />
                                                </td>
                                            </tr>
                                        <?php } ?>

                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th></th>
                                            <th> Tên khách hàng</th>
                                            <th> Email</th>
                                            <th> Điện thoại</th>
                                            <th>Ngày tạo</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- //////////////////DELETE///////////////////--> 
<div class="modal fade" id="del" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header  blue-background">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                <h4 class="modal-title custom_align" id="Heading">XÓA ĐƠN HÀNG</h4>
            </div>
            <div class="modal-body">
                <p>Bạn có chắc chắn muốn xóa đơn hàng này khỏi hệ thống.</p>

            </div>
            <div class="modal-footer ">
                <span id="btn-del"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
            </div>
        </div>
        <!-- /.modal-content --> 
    </div>
    <!-- /.modal-dialog --> 
</div>

