<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-plus'></i>
                        <span> Mạng Xã hội</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            <li>                                
                                <button class="btn btn-primary" onclick="submitform()"><i class="icon-save"></i> Lưu</button>
                            </li> 
                            <li>                                
                                <button class="btn btn-primary" onclick="resetform()"><i class="icon-refresh"></i> Nhập lại</button>
                            </li>                                                  

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box'>
                    <?php
                    if(isset($alert)){
                        echo $alert;
                    }
                    ?>
                    <div class='box-header'>
                        <!--<div class='title'>Add User</div>-->
                        <button rel=".tab-content1" class="btn background-new">Thông tin chung</button>
                        <!-- <button rel=".tab-content2" class="btn">Cấu hình SEO</button>
                       <div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>-->
                    </div>
                    <div class='box-content'>
                        
                        <form method="post" id="form-admin" class='form form-horizontal validate-form' style='margin-bottom: 0;' enctype="multipart/form-data">
                            <div class="content-tab tab-content1">
                                  <div class='form-group'>
                                        <label class='control-label col-sm-3' for='validation_name'>Facebook </label>
                                        <div class='col-sm-6 controls'>
                                            <input class='form-control'  value="<?php echo $data_setting['facebook']?>" id='validation_name' name="facebook"  placeholder='Facebook' type='text' >
                                        </div>
                                    </div> 
                                 <div class='form-group'>
                                        <label class='control-label col-sm-3' for='validation_name'>Twiter</label>
                                        <div class='col-sm-6 controls'>
                                            <input class='form-control' value="<?php echo $data_setting['twiter']?>" id='validation_name' name="twiter"  placeholder='Twiter' type='text' >
                                        </div>
                                    </div>
                                 <div class='form-group'>
                                        <label class='control-label col-sm-3' for='validation_name'>Google+</label>
                                        <div class='col-sm-6 controls'>
                                            <input class='form-control'  value="<?php echo $data_setting['google']?>" id='validation_name' name="google"  placeholder='Google' type='text' >
                                        </div>
                                    </div>
                               <div class='form-group'>
                                        <label class='control-label col-sm-3' for='validation_name'>Youtube</label>
                                        <div class='col-sm-6 controls'>
                                            <input class='form-control'  value="<?php echo $data_setting['printer']?>" id='validation_name' name="printer"  placeholder='Pinterest' type='text' >
                                        </div>
                                </div>
                                 <div class='form-group'>
                                        <label class='control-label col-sm-3' for='validation_name'>Fan Page</label>
                                        <div class='col-sm-6 controls'>
                                            <textarea class='form-control' rows="15" name="fanpage"><?php echo $data_setting['fanpage']?></textarea>
                                           
                                        </div>
                                </div>          
                                     
                            </div>

                        </form>
                    </div>

                </div>
            </div>
        </div>              
    </div>
</div>