<div class="box-slider-left">
    <div class="box-product">
        <h3 class="title-product-3">
            <span>Tài khoản của tôi</span>
        </h3>
        <div class="title-info">
            Từ trang này bạn có thể xem các đơn đặt hàng của bạn, cập nhật chi tiết tài khoản của bạn và nhiều hơn nữa. Chọn một trong những tùy chọn dưới đây để thao tác:
        </div>
    </div>
    <div class="box-contact">
        <div class="box-checkout-left22">
            <div class="box-slider-right">
                <div class="box-left-news">
                    <a href=""><img src="<?php echo WEB_STATIC ?>/images/thongtintk.png" alt=""></a>
                </div>
            </div>
            <div class="box-slider-left">
                <div class="box-left-news">
                    <a href="<?php echo WEB_PATH ?>/tai-khoan/thong-tin-tai-khoan.html" class="color3">Thông tin tài khoản</a>
                    <p>Cập nhật thông tin cá nhân, địa chỉ Email và(hoặc) thay đổi mật khẩu truy cập website của bạn.</p>
                </div>
            </div>
        </div>
        <div class="box-checkout-right22">
            <div class="box-slider-right">
                <div class="box-left-news">
                    <a href=""><img src="<?php echo WEB_STATIC ?>/images/quanlydonhang.png" alt=""></a>
                </div>
            </div>
            <div class="box-slider-left">
                <div class="box-left-news">
                    <a href="<?php echo WEB_PATH ?>/tai-khoan/quan-ly-don-hang.html" class="color3">Quản lý đơn hàng</a>
                    <p>Xem trạng thái mỗi đơn hàng đã đặt tại website</p>
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>

</div>