<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-plus'></i>
                        <span>Thêm mới tài khoản</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            <li>
                                <a href='index.html'>
                                    <button class="btn btn-danger"><i class="icon-arrow-left"></i> Quay lại</button>
                                </a>
                            </li>                        
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box'>
                    <div class='box-header blue-background'>
                        <div class='title'>Add User</div>
                        <div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>
                    </div>
                    <div class='box-content'>
                        <form method="post" class='form form-horizontal validate-form' style='margin-bottom: 0;'>

                            <div class="row">   
                            <div class='form-group col-sm-6'>
                                <label class='control-label col-sm-3' for='validation_name'>Tài khoản</label>
                                <div class='col-sm-9 controls'>
                                    <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_name' name="username"  placeholder='Tài khoản' type='text' >
                                </div>
                            </div>
                            <div class='form-group col-sm-6'>
                                <label class='control-label  col-sm-3' for='validation_name'>Họ tên</label>
                                <div class='col-sm-9 controls'>

                                    <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_namef' name="fullname"  placeholder='Họ tên' type='text' >
                                </div>
                            </div>
                            </div>
                            <div class="row">
                            <div class='form-group col-sm-6'>
                                <label class='control-label  col-sm-3' for='validation_name'>Email</label>
                                <div class='col-sm-9 controls'>

                                    <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_email' name="email"  placeholder='Email' type='text' >
                                </div>
                            </div>
                            <div class='form-group col-sm-6'>
                                <label class='control-label  col-sm-3' for='validation_name'>Điện thoại</label>
                                <div class='col-sm-9 controls'>
                                    <input class='form-control'  name="fullname"  placeholder=' Điện thoại' type='text' >
                                </div>
                            </div>
                            </div>
                            <div class="row">
                            <div class='form-group col-sm-6'>
                                <label class='control-label  col-sm-3' for='validation_name'>Điạ chỉ</label>
                                <div class='col-sm-9 controls'>

                                    <input class='form-control'  name="fullname"  placeholder=' Địa chỉ' type='text' >
                                </div>
                            </div>
                            <div class='form-group col-sm-6'>
                                <label class='control-label col-sm-3' for='validation_name'>Yahoo</label>
                                <div class='col-sm-9 controls'>

                                    <input class='form-control'  name="yahoo"  placeholder='Yahoo' type='text' >
                                </div>
                            </div>
                            </div>
                            <div class="row">
                            <div class='form-group col-sm-6'>
                                <label class='control-label col-sm-3' for='validation_name'>Skype</label>
                                <div class='col-sm-9 controls'>

                                    <input class='form-control'  name="skype"  placeholder='Skype' type='text' >
                                </div>
                            </div>
                            <div class='form-group col-sm-6'>
                                <label class='control-label col-sm-3' for='validation_select'>Giới tính</label>
                                <div class='col-sm-9 controls'>
                                    <select class='form-control'  name='permission'>
                                        <option> Chọn giới tính</option>
                                        <option value="0">Nam</option>
                                        <option value="1"> Nữ</option>
                                    </select>
                                </div>
                            </div>
                            </div>
                            <div class="row">
                            <div class='form-group col-sm-6'>
                                <label class='control-label  col-sm-3' for='validation_password'> Mật khẩu</label>
                                <div class='col-sm-9 controls'>
                                    <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_password' name="password"  placeholder='Password' type='password' >
                                </div>
                            </div>
                            <div class='form-group col-sm-6'>
                                <label class='control-label col-sm-3' for='validation_password'>Xác nhận mật khẩu</label>
                                <div class='col-sm-9 controls'>
                                    <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_passwords' name="repass"  placeholder='Retype password' type='password' >
                                </div>
                            </div>
                            </div>
                            <div class="row">
                            <div class="form-group col-sm-6">
                                <label class="col-md-3 control-label">Trạng thái</label>
                                <div class="col-sm-9">
                                    <label class="radio radio-inline">
                                        <input type="radio" value="1" name="status" checked>
                                         Hoạt động
                                    </label>
                                    <label class="radio radio-inline">
                                        <input type="radio" value="0" name="status">
                                        Không hoạt động
                                    </label>

                                </div>
                            </div>
                            <div class='form-group col-sm-6'>
                                <label class='control-label col-sm-3' for='validation_select'>Phân quyền</label>
                                <div class='col-sm-9 controls'>
                                    <select class='form-control'  name='permission'>
                                        <option> Chọn nhóm quyền</option>
                                        <option value="1"> Quản trị hệ thống</option>
                                        <option value="2"> Quản trị nội dung</option>
                                        <option value="3"> Quản trị bán hàng</option>
                                        <option value="4"> Nhân viên bán hàng</option>
                                    </select>
                                </div>
                            </div>
                            </div>
                            <div class="row">
                            <div class='form-group col-sm-6'>
                                <label class='control-label  col-sm-3' for='validation_name'>Ảnh đại diện</label>
                                <div class='col-sm-2 controls'>                                                                                                           
                                    <span class='btn btn-success fileinput-button'>
                                        <i class='icon-plus icon-white'></i>
                                        <span> Chọn ảnh...</span>
                                        <input data-bfi-disabled='' multiple='' name='imgicon' id="asd" type='file'>
                                    </span>

                                </div>
                                <div class="col-sm-4"><img style="width:100%"id="img" src="" /></div>
                            </div>
                            </div>
                            <div class='form-actions' style='margin-bottom:0'>
                                <div class='row'>
                                    <div class='col-sm-9 col-sm-offset-3'>
                                        <button class='btn btn-primary' name="send" type='submit'>
                                            <i class='icon-save'></i>
                                            Lưu
                                        </button>
                                        <span style="color: #f01b16; font-style: italic;"><?php
                                            if (isset($thongbao)) {
                                                echo $thongbao;
                                            }
                                            ?></span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>              
    </div>
</div>