<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-th'></i>
                        <span>Quản lý tin tức</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            <li>
                                <a href='<?php echo WEB_PATH ?>/system/news/add'>
                                    <button class="btn btn-primary"><i class="icon-plus"></i> Thêm mới</button>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box bordered-box orange-border' style='margin-bottom:0;'>
                   <!-- <div class='box-header blue-background'>
                        <div class='title'>List User</div>
                        <div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>
                    </div>-->
                    <div class='box-content box-no-padding'>
                        <div class='responsive-table'>
                            <div class='scrollable-area'>
                                <table class='data-table-column-filter table table-bordered table-striped' style='margin-bottom:0;'>
                                    <thead>
                                        <tr>
                                            <th>
                                               STT
                                            </th>
                                            <th>
                                                Tiêu đề
                                            </th>
                                            <th>
                                                Danh mục
                                            </th>
                                            <th>
                                                Ngày đăng
                                            </th>
                                            <th>
                                                Người đăng
                                            </th>
                                            <th>
                                                Trạng thái
                                            </th>																
                                            <th>
                                                Action
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                        
                                        <?php 
                                        $stt='';
                                        foreach ($data as $key => $value) { ?>

                                            <tr>
                                                <td><?php echo $stt++; ?></td>
                                                <td><?php echo $value['news_title']; ?></?php?></td>
                                                <td><?php echo $value['name']; ?></td>                                              
                                                <td><?php echo date('d-m-Y', strtotime($value['news_date'])); ?></td>
                                                 <td><?php echo $value['fullname']; ?></td>
                                                <td>
                                                    <?php
                                                    if ($value['news_status'] == 1) {
                                                        echo '<a href='.WEB_PATH.'/system/news/status/'.$value['id'].'/'.$value['news_status'].'
                                                        <button class="btn btn-xs btn-success"><i class="icon-check"></i></button></a>';
                                                    } else {
                                                        echo '<a href='.WEB_PATH.'/system/news/status/'.$value['id'].'/'.$value['news_status'].'
                                                        <button class="btn btn-xs btn-danger"><i class="icon-minus-sign"></i></button></a>';
                                                    }
                                                    ?>
                                                </td>
                                                <td>
                                                    <div class='text-right'>
                                                        <a class='btn btn-primary btn-xs' href='<?php echo WEB_PATH; ?>/system/news/edit/<?php echo $value['id']; ?>'>
                                                            <i class='icon-edit'></i>
                                                        </a>
                                                         <a onclick="deleteaction(<?php echo $value['id']; ?>)"class='btn btn-danger btn-xs'>
                                                            <i class='icon-remove'></i>
                                                        </a>
                                                    </div>
                                                    <input type="hidden" id="url" value="news/delete/" />
                                                </td>
                                            </tr>
                                        <?php } ?>
                                        
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th></th>
                                            <th> Tiêu đề</th>
                                            <th> Danh mục</th>
                                            <th> Ngày đăng</th>
                                            <th> Trạng thái</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- //////////////////DELETE///////////////////--> 
<div class="modal fade" id="del" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header  blue-background">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                <h4 class="modal-title custom_align" id="Heading">Xóa tin túc</h4>
            </div>
            <div class="modal-body">
                <p>Bạn có chắc chắn muốn xóa bài viết này</p>

            </div>
            <div class="modal-footer ">
                <span id="btn-del"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
            </div>
        </div>
        <!-- /.modal-content --> 
    </div>
    <!-- /.modal-dialog --> 
</div>

<div class="modal fade" id="repass" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header  blue-background">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                <h4 class="modal-title custom_align" id="Heading">RESET PASSWORD</h4>
            </div>
            <div class="modal-body">
                <p>Reset password successfull</p>
                <p>Password được khôi phục về mặc định là: 123456</p>

            </div>
            <div class="modal-footer ">
                <span id="btn-del"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
            </div>
        </div>
        <!-- /.modal-content --> 
    </div>
    <!-- /.modal-dialog --> 
</div>