<h1 class="page-heading">
    <span class="page-heading-title2"><?php echo $data_detail['news_title'] ?></span>
</h1>
<article class="entry-detail">
    <div class="entry-meta-data">                     
        <span class="date"><i class="fa fa-calendar"></i> <?php echo date('d-m-Y', strtotime($data_detail['news_date'])); ?></span>

    </div>

    <div class="content-text clearfix view-news">
        <?php echo $data_detail['news_contents'] ?>
    </div>
    <span class="author-news"><?php echo $data_detail['fullname'] ?></span>
</article>
<!-- Related Posts -->
<div class="single-box slide-news">
    <h2>Tin mới</h2>
    <ul class="related-posts owl-carousel" data-dots="false" data-loop="true" data-nav = "true" data-margin = "30" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":2},"1000":{"items":3}}'>
        <?php
        $i = 0;
        foreach ($data_new as $key => $value) {
            if (++$i > 10)
                break;
            ?>
            <li class="post-item">
                <article class="entry">
                    <div class="entry-thumb image-hover2">
                        <a href="<?php echo WEB_PATH . '/tin-tuc/' . $value['news_alias'] . '.html' ?>">
                            <img src="<?php echo WEB_IMG . $value['news_img'] ?>" alt="<?php echo $value['news_title'] ?>" onerror=this.src="<?php echo WEB_IMG ?>/images/imgdefault.jpg" />
                        </a>
                    </div>
                    <div class="entry-ci">
                        <h3 class="entry-title"><a href="<?php echo WEB_PATH . '/tin-tuc/' . $value['news_alias'] . '.html' ?>"><?php echo $value['news_title'] ?></a></h3>
                        <div class="entry-meta-data">                        
                            <span class="date">
                                <i class="fa fa-calendar"></i> <?php echo date('d-m-Y', strtotime($value['news_date'])); ?>
                            </span>
                        </div>
                        <div class="entry-more">
                            <a href="<?php echo WEB_PATH . '/tin-tuc/' . $value['news_alias'] . '.html' ?>"> Chi tiết</a>
                        </div>
                    </div>
                </article>
            </li>
<?php } ?>
    </ul>
</div>
<!-- ./Related Posts -->