<!DOCTYPE HTML>
<html>
<head>
<title>OOPS! - Could not Find it</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href='http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="<?php echo WEB_STATIC ?>/theme/assets/lib/bootstrap/css/bootstrap.min.css" />
<style type="text/css">
body{
	font-family: 'Love Ya Like A Sister', cursive;
}
body{
	background:#eaeaea;
}	
.wrap{
	margin:0 auto;
	width:100%;
        margin: 0 auto;
}
.logo{
	text-align:center;
	margin-top:20px;
}
.logo img{
	
}
.logo p{
	color:#272727;
	font-size:35px;
	margin-top:1px;
}	
.logo p span{
	color:lightgreen;
}	
.sub p{	
	text-align:center;
	margin-top:20px;
	font-size:17px;
}
.footer{
	color:black;
	position:absolute;
	right:10px;
	bottom:10px;
}	
.footer a{
	color:rgb(114, 173, 38);
}	
</style>
</head>


<body>
<script type = "text/javascript">
setTimeout(function()
{
location.pathname= "/"
},5000);
</script>
 <div class="wrap">
	<div class="logo"></br>
			<p>Bài viết đã quá cũ hoặc không tìm thấy</p>
			<p>Chúng tôi xin lỗi về sự bất tiện này!</p>
                        <a href="<?php echo WEB_PATH?>"><img src="<?php echo WEB_IMG ?>images/4041.PNG" class=" col-sm-offset-4 col-md-offset-4 img-responsive"/></a>
	</div>
			<div class="sub">
			  <p>Bạn sẽ được chuyển về trang chủ sau 5 giây...</p>
			</div>
 </div>	

	<div class="footer">
	 Giadung88.com   -   Giadung88.vn
	</div>
	
</body>