<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-plus'></i>
                        <span>  Cấu hình Email</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            <li>                                
                                <button class="btn btn-primary" onclick="submitform()"><i class="icon-save"></i> Lưu</button>
                            </li> 
                            <li>                                
                                <button class="btn btn-primary" onclick="resetform()"><i class="icon-refresh"></i> Nhập lại</button>
                            </li>                                                  

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box'>
                    <?php
                    if(isset($alert)){
                        echo $alert;
                    }
                    ?>
                    <div class='box-header'>
                        <!--<div class='title'>Add User</div>-->
                        <button rel=".tab-content1" class="btn background-new">Thông tin chung</button>
                        <!-- <button rel=".tab-content2" class="btn">Cấu hình SEO</button>
                       <div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>-->
                    </div>
                    <div class='box-content'>
                        
                        <form method="post" id="form-admin" class='form form-horizontal validate-form' style='margin-bottom: 0;' enctype="multipart/form-data">
                            <div class="content-tab tab-content1">
                                  <div class='form-group'>
                                        <label class='control-label col-sm-4' for='validation_name'>Email gửi thông tin đặt hàng  </label>
                                        <div class='col-sm-6 controls'>
                                            <input class='form-control'  data-rule-minlength='5' data-rule-required='true' value="<?php echo $data_setting['email_admin']?>" id='validation_name1' name="email_admin"   type='text' >
                                        </div>
                                    </div> 
                                 <div class='form-group'>
                                        <label class='control-label col-sm-4' for='validation_name'>Email nhận thông tin đặt hàng</label>
                                        <div class='col-sm-6 controls'>
                                            <input class='form-control' data-rule-minlength='5' data-rule-required='true' value="<?php echo $data_setting['email_customer']?>" id='validation_name2' name="email_customer"   type='text' >
                                        </div>
                                    </div>
                                 <div class='form-group'>
                                        <label class='control-label col-sm-4' for='validation_name'>Email Hệ Thống (Gmail)</label>
                                        <div class='col-sm-6 controls'>
                                            <input class='form-control'  data-rule-minlength='5' data-rule-required='true' value="<?php echo $data_setting['email_system']?>" id='validation_name3' name="email_system"   type='text' >
                                        </div>
                                    </div>
                               <div class='form-group'>
                                        <label class='control-label col-sm-4' for='validation_name'> Mật khẩu Email hệ thống</label>
                                        <div class='col-sm-6 controls'>
                                            <input class='form-control' data-rule-minlength='5' data-rule-required='true'  value="<?php echo $data_setting['pass_system']?>" id='validation_name4' name="pass_system"   type='text' >
                                        </div>
                                </div>
                                         
                                     
                            </div>

                        </form>
                    </div>

                </div>
            </div>
        </div>              
    </div>
</div>