<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-plus'></i>
                        <span>Thêm mới danh mục sản phẩm</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            <li>                                
                                <button class="btn btn-primary" onclick="submitform()"><i class="icon-save"></i> Lưu</button>
                            </li> 
                            <li>                                
                                <button class="btn btn-primary" onclick="resetform()"><i class="icon-refresh"></i> Nhập lại</button>
                            </li>
                            <li>
                                <a href='<?php echo WEB_PATH.'/system/product/category.html'?>'>
                                    <button class="btn btn-primary"><i class="icon-arrow-left"></i> Quay lại</button>
                                    
                                </a>
                             </li> 

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box'>
                    <?php
                    if(isset($alert)){
                        echo $alert;
                    }
                    ?>
                   
                    <div class='box-header'>
                        <!--<div class='title'>Add User</div>-->
                        <button rel=".tab-content1" class="btn background-new">Thông tin chung</button>
                        <button rel=".tab-content2" class="btn">Cấu hình SEO</button>
                        <!--<div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>-->
                    </div>
                    <div class='box-content'>
                        <form id="form-admin" method="post" class='form form-horizontal validate-form' style='margin-bottom: 0;' enctype="multipart/form-data">
                            <div class="content-tab tab-content1">
                            <div class="row">   
                                <div class='form-group col-sm-12'>
                                    <label class='control-label col-sm-3' for='validation_name'>Tên danh mục</label>
                                    <div class='col-sm-7 controls'>
                                        <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_name' name="name"  placeholder='Tên danh mục' type='text' >
                                    </div>
                                </div>
                                <div class='form-group col-sm-12'>
                                    <label class='control-label col-sm-3' for='validation_select'>Danh mục cha</label>
                                    <div class='col-sm-7 controls'>
                                        <select class='form-control'  name='parent'>
                                            <option> Chọn danh mục </option>
                                            <?php foreach ($data_cat as $key=>$value){
                                                    if($value['parent']=='0'){
                                                        $PARENT_2 =$data_parent[$value['id']];                                                        
                                                    ?>
                                                <option value="<?php echo $value['id']?>"><?php echo $value['name']?></option>
                                                <?php
                                                //cấp 2
                                                if(count($PARENT_2)>0){
                                                    foreach ($PARENT_2 as $k2=>$vl2){
                                                        echo '<option value="'.$vl2['id'].'">- - '.$vl2['name'].'</option>';
                                                    //cấp 3
                                                        $PARENT_3=$data_parent[$vl2['id']];
                                                        if(count($PARENT_3)>0){
                                                            foreach ($PARENT_3 as $k3=>$vl3){
                                                                 echo '<option value="'.$vl3['id'].'">- - - -'.$vl3['name'].'</option>';
                                                            }
                                                        }//End cấp 3
                                                    }
                                                    
                                                }//End cấp 2
                                                ?>
                                              
                                                <?php                                                 
                                                    }
                                                }//End cấp 1
                                                ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-sm-12">
                                    <label class="col-md-3 control-label">Hiển thị trang chủ</label>
                                    <div class="col-sm-6">
                                        <label class="radio radio-inline">
                                            <input type="radio" value="1" name="show_index" >
                                            Có
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="0" name="show_index">
                                            Không 
                                        </label>

                                    </div>
                                </div>
                               
                                <div class="form-group col-sm-12">
                                    <label class="col-md-3 control-label">Trạng thái</label>
                                    <div class="col-sm-7">
                                        <label class="radio radio-inline">
                                            <input type="radio" value="1" name="status" checked>
                                            Hiển thị
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="0" name="status">
                                            Không  hiển thị
                                        </label>

                                    </div>
                                </div>
                                 <div class="form-group col-sm-12">
                                    <label class="col-md-3 control-label">Màu nền</label>
                                    <div class="col-sm-7">
                                        <label class="radio radio-inline">
                                            <input type="radio" value="1" name="background" checked>
                                            <span class='mau mau1'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="2" name="background">
                                            <span class='mau mau2'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="3" name="background" >
                                            <span class='mau mau3'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="4" name="background">
                                            <span class='mau mau4'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="5" name="background" >
                                            <span class='mau mau5'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="6" name="background">
                                            <span class='mau mau6'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="7" name="background" >
                                            <span class='mau mau7'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="8" name="background">
                                            <span class='mau mau8'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="9" name="background" >
                                            <span class='mau mau9'></span>
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="10" name="background">
                                            <span class='mau mau10'></span>
                                        </label>
                                    </div>
                                </div>
                                 <div class='form-group col-sm-12'>
                                    <label class='control-label col-sm-3' for='validation_name'>Nhân Viên hỗ trợ</label>
                                    <div class='col-sm-7 controls'>
                                        <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_user' name="user"  placeholder='Nhân viên hỗ trợ' type='text' >
                                    </div>
                                </div>
                                 <div class='form-group col-sm-12'>
                                    <label class='control-label col-sm-3' for='validation_name'>Điện thoại nhân viên</label>
                                    <div class='col-sm-7 controls'>
                                        <input class='form-control' data-rule-minlength='2' data-rule-required='true' id='validation_phone_name' name="phone"  placeholder='Điện thoại nhân viên' type='text' >
                                    </div>
                                </div>
                                 <div class='form-group'>
                                        <label class='control-label  col-sm-3' for='validation_name'> Ảnh Mô tả</label>
                                       
                                        <div class='col-sm-2 controls'>                                                                                                           
                                            <span class='btn btn-success fileinput-button'>
                                                <i class='icon-upload-alt icon-white'></i>
                                                <span> Chọn ảnh...</span>
                                                <input data-bfi-disabled='' multiple='' name='img' id="asd" type='file'>
                                            </span>

                                        </div>
                                        <div class="col-sm-4"><img style="width:100%"id="img" src="" /></div>
                                        
                                    </div>
                                                
                                <div class='form-group'>
                                        <label class='control-label  col-sm-3' for='validation_name'>Icon</label>
                                       
                                        <div class='col-sm-2 controls'>                                                                                                           
                                            <span class='btn btn-success fileinput-button'>
                                                <i class='icon-upload-alt icon-white'></i>
                                                <span> Chọn ảnh...</span>
                                                <input data-bfi-disabled='' multiple='' name='icon' id="favicon" type='file'>
                                            </span>

                                        </div>
                                        <div class="col-sm-4"><img id="img-favicon" src="" /></div>
                                        
                                    </div>
                            </div>                         

                           
                            <div class="row">
                                <div class='form-group col-sm-12'>
                                    <label class="col-sm-3 control-label" for='validation_textarea'>Mô tả </label>
                                    <div class="box-content col-sm-7">
                                        <textarea class="form-control"  id="validation_name7" placeholder="Mô tả" name="description" rows="5"></textarea>
                                    </div>
                                </div>
                            </div>                      
                            
                            </div>
                            <div class="content-tab tab-content2">
                                <div class="row">
                                <div class='form-group col-sm-12'>
                                    <label class="col-sm-2 control-label">Tiêu đê</label>
                                    <div class="box-content col-sm-8">
                                        <textarea class="form-control" data-rule-required="true" id="validation_name7" placeholder="Seo Title" name="seo_title" rows="5"></textarea>
                                    </div>
                                </div>
                            </div>
                                <div class="row">
                                <div class='form-group col-sm-12'>
                                    <label class="col-sm-2 control-label">Meta Keyword</label>
                                    <div class="box-content col-sm-8">
                                        <textarea class="form-control" data-rule-required="true" id="validation_name7" placeholder="Seo Keyword" name="seo_keyword" rows="5"></textarea>
                                    </div>
                                </div>
                            </div>
                                <div class="row">
                                <div class='form-group col-sm-12'>
                                    <label class="col-sm-2 control-label">Meta Description</label>
                                    <div class="box-content col-sm-8">
                                        <textarea class="form-control" data-rule-required="true" id="validation_name7" placeholder="Seo description" name="seo_description" rows="5"></textarea>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>              
    </div>
</div>