<div class='row' id='content-wrapper'>
    <div class='col-xs-12'>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='page-header'>
                    <h1 class='pull-left'>
                        <i class='icon-plus'></i>
                        <span>Sửa chất liệu sản phẩm</span>
                    </h1>
                    <div class='pull-right'>
                        <ul class='breadcrumb'>
                            <li>                                
                                <button class="btn btn-primary" onclick="submitform()"><i class="icon-save"></i> Lưu</button>
                            </li> 
                            <li>                                
                                <button class="btn btn-primary" onclick="resetform()"><i class="icon-refresh"></i> Nhập lại</button>
                            </li>
                            <li>
                                <a href='<?php echo WEB_PATH.'/system/product/chatlieu.html'?>'>
                                    <button class="btn btn-primary"><i class="icon-arrow-left"></i> Quay lại</button>
                                    
                                </a>
                             </li> 

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-sm-12'>
                <div class='box'>
                    <?php
                    if(isset($alert)){
                        echo $alert;
                    }
                    ?>
                   
                    <div class='box-header'>
                        <!--<div class='title'>Add User</div>-->
                        <button rel=".tab-content1" class="btn background-new">Thông tin chung</button>
                        <!--<button rel=".tab-content2" class="btn">Cấu hình SEO</button>
                        <div class='actions'>
                            <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
                            </a>

                            <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
                            </a>
                        </div>-->
                    </div>
                    <div class='box-content'>
                        <form id="form-admin" method="post" class='form form-horizontal validate-form' style='margin-bottom: 0;' enctype="multipart/form-data">
                            <div class="content-tab tab-content1">
                            <div class="row">   
                                <div class='form-group col-sm-12'>
                                    <label class='control-label col-sm-3' for='validation_name'> Chất liệu</label>
                                    <div class='col-sm-6 controls'>
                                        <input class='form-control' data-rule-minlength='2' value="<?php echo $data_detail['name']?>" data-rule-required='true' id='validation_name' name="name"  placeholder='Tên xuất xứ' type='text' >
                                    </div>
                                </div>
                               <div class="form-group col-sm-12">
                                    <label class="col-md-3 control-label">Hiển thị</label>
                                    <div class="col-sm-6">
                                        <label class="radio radio-inline">
                                            <input type="radio" value="1" <?php if($data_detail['status']==='1'){ echo 'checked';}?> name="status" >
                                            Có
                                        </label>
                                        <label class="radio radio-inline">
                                            <input type="radio" value="0" <?php if($data_detail['status']==='0'){ echo 'checked';}?> name="status">
                                            Không 
                                        </label>

                                    </div>
                                </div>
                            </div>                           
                            </div>
                            
                        </form>
                    </div>

                </div>
            </div>
        </div>              
    </div>
</div>